name: module3_task0

on:
  push:
    paths:
      - 'module3_task0/**'
  schedule:
    - cron : '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout release
        uses: actions/checkout@v3 # Clona el repositorio
      - name: validate makefile
        run: |
          cd module3_task0
          make help

