---
name: module3_task0
on:
  push:
    paths:
      - 'module3_task0/**'
  schedule:
    - cron: '0 8 * * *'
jobs:
  task0:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: validate makefile
        run: |
          cd module3_task0
          make help
