---
name: module3_task5
on:
  pull_request:
    branches:
      - 'main'
      - 'master'
  push:
    paths:
      - 'module3_task5/**'
    tags:
      - "*.*.*"
    branches:
      - 'main'
      - 'master'
  schedule:
    - cron: '0 8 * * *'
jobs:
  task1:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: setup
        run: |
          cd module3_task5
          ./setup.sh
      - name: validate makefile
        run: |
          cd module3_task5
          make build
      - name: create package
        run: |
          cd module3_task5
          make package
      - name: make lint
        run: |
          cd module3_task5
          make lint
      - name: unit-tests
        run: |
          cd module3_task5
          make unit-tests
      - name: integration-tests
        run: |
          cd module3_task5
          make integration-tests
      - name: validate
        run: |
          cd module3_task5
          make validate
      - name: Archive awesome compressed
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./module3_task5/awesome-website.zip
            ./module3_task5/DEPLOY.md
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/*.*.*')
        with:
          files: module3_task5/awesome-website.zip
          body_path: ./module3_task5/DEPLOY.md
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./module3_task5/dist"
          production-branch: main
          github-token: ${{ secrets.REPO_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
