---
name: module3_task2
on:
  push:
    paths:
      - 'module3_task2/**'
  schedule:
    - cron: '0 8 * * *'
jobs:
  task1:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: setup
        run: |
          cd module3_task2
          ./setup.sh
      - name: validate makefile
        run: |
          cd module3_task2
          make build
      - name: create package
        run: |
          cd module3_task2
          make package
      - name: make lint
        run: |
          cd module3_task2
          make lint
      - name: Archive awesome compressed
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./module3_task2/awesome-website.zip
            ./module3_task2/DEPLOY.md
