---
name: release_drafter

on:
  push:
    paths:
      - 'module3_task5/**'
    branches:
      - 'main'
      - 'master'
  pull_request:
    branches:
      - 'main'
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
