---
name: Release Drafter

on:
  push:
    paths:
      - 'module3_task4/**'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
